// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/ropel12/project-3/app/entities"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: db, user
func (_m *UserRepo) Create(db *gorm.DB, user entities.User) error {
	ret := _m.Called(db, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.User) error); ok {
		r0 = rf(db, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: db, user
func (_m *UserRepo) Delete(db *gorm.DB, user entities.User) error {
	ret := _m.Called(db, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.User) error); ok {
		r0 = rf(db, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: db, email
func (_m *UserRepo) FindByEmail(db *gorm.DB, email string) (*entities.User, error) {
	ret := _m.Called(db, email)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) (*entities.User, error)); ok {
		return rf(db, email)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *entities.User); ok {
		r0 = rf(db, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = rf(db, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: db, id
func (_m *UserRepo) GetById(db *gorm.DB, id int) (*entities.User, error) {
	ret := _m.Called(db, id)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) (*entities.User, error)); ok {
		return rf(db, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, int) *entities.User); ok {
		r0 = rf(db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, int) error); ok {
		r1 = rf(db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: db, user
func (_m *UserRepo) Update(db *gorm.DB, user entities.User) (*entities.User, error) {
	ret := _m.Called(db, user)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.User) (*entities.User, error)); ok {
		return rf(db, user)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.User) *entities.User); ok {
		r0 = rf(db, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, entities.User) error); ok {
		r1 = rf(db, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
